"""add error message to document

Revision ID: 10a85dd6120d
Revises: cf73f470756d
Create Date: 2026-08-12 04:34:28.642889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10a85dd6120d'
down_revision: Union[str, Sequence[str], None] = 'cf73f470756d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'error_message')
    # ### end Alembic commands ###
