"""add embedding to document chunks

Revision ID: b340b7fbdc8a
Revises: ea3b11e28810
Create Date: 2026-08-09 16:09:44.911395

"""
from typing import Sequence, Union

import pgvector
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b340b7fbdc8a'
down_revision: Union[str, Sequence[str], None] = 'ea3b11e28810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'embedding')
    # ### end Alembic commands ###
