"""replace storage path with key

Revision ID: cf73f470756d
Revises: b340b7fbdc8a
Create Date: 2026-08-10 16:02:14.777844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf73f470756d'
down_revision: Union[str, Sequence[str], None] = 'b340b7fbdc8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('storage_key', sa.String(length=500), nullable=False))
    op.drop_column('documents', 'storage_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('storage_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_column('documents', 'storage_key')
    # ### end Alembic commands ###
