"""update documents 2

Revision ID: 9401f3f4e883
Revises: c379360c1718
Create Date: 2026-08-09 12:55:10.468121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9401f3f4e883'
down_revision: Union[str, Sequence[str], None] = 'c379360c1718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'content_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('documents', 'size',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('documents', 'content_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
